[package]
name = "Spider2"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = { version = "2", features = ["sitemap"
    , "smart","chrome","chrome_intercept"
    ,"chrome_stealth"] }
fast_html2md = "=0.0.11"
env_logger = "0.11.6"
